config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  # devise_for :clients
  # devise_for :mentors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :clients, :controllers => { registrations: 'clients/registrations' }
  devise_for :mentors, :controllers => { registrations: 'mentors/registrations' }

  get '/offers_fetch', to: 'pages#offers_fetch'
  get '/offers_show/:id', to: 'pages#offers_show', as: 'offers_show'
  post '/new_booking', to: 'pages#new_booking', as: 'new_booking'

  get '/new_offer', to: 'mentors/offers#new', as: "new_offer"
  post '/create_offer', to: 'mentors/offers#create', as: "create_offer"

  get '/new_slot', to: 'mentors/slots#new', as: "new_slot"
  post '/create_slot', to: 'mentors/slots#create', as: "create_slot"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/index.html.erb
<h1>Index</h1>

<div class="client_sign_in" >
  <%= link_to 'Client Sign In', new_client_session_path %>
</div>
<br>
<div class="mentor_sign_in" >
  <%= link_to 'Mentor Sign In', new_mentor_session_path %>
</div>

<% if current_client %>
  <%= link_to 'sign out', destroy_client_session_path, method: :delete %>
<% end %>

<% if current_mentor %>
  <%= link_to 'sign out', destroy_mentor_session_path, method: :delete %>
<% end %>

<% @category.each do |cat| %>
  <button type="button" class="category" id="<%= cat.id %>" ><%= cat.name %></button>
<% end %>

<div id="show_offers" class="d-flex" >
  
</div>

app/views/pages/offers_show.html.erb
<h1><%= @offer["name"] %></h1>
<p><%= @offer["description"] %></p>
<b>Price: ₹ <%= @offer["price"] %></b>
<script>console.log(<%= current_client %>)</script>
<br><br>

<h1>Change Booking according to slots!!!!!!!!!</h1>

<% if current_client %>

<h3>Slots Available</h3>
  <% @all_slots = [] %>
  <% @slots.each do |sl| %>
    <% @all_slots.push([sl['start_time'].strftime("%I:%M %p") + " - " + sl['end_time'].strftime("%I:%M %p"),sl['id']]) %>
    <div class="card" >
      <div class="card-body" >
        <div> <span>Start Time :</span> <%= sl.start_time.strftime("%I:%M %p") %> </div>
        <div> <span>End Time :</span> <%= sl.end_time.strftime("%I:%M %p") %> </div>
        <div> <span>Frequency :</span> 
        <% sl.frequency.each_with_index do |fre,i| %>
        <% if fre!= "" %>
        <% if i==1 %>
          <%= fre %>
        <% else %>
          <%= ", " + fre %>
        <% end %>
        <% end %>
        <% end %>
         </div>
      </div>
    </div>
    <% end %>
<% if params['format'] %>
  <h3><%= params['format'] %></h3>
<% end %>
<%= form_for @booking, url: new_booking_path do |f| %>
  <%= f.text_field :mentor_id, {value: @offer["mentor"]["id"], hidden: "true"} %>
  <%= f.text_field :client_id, {value: current_client.id, hidden: "true"} %>
  <%= f.text_field :offer_id, {value: @offer["id"], hidden: "true"} %>
  <%= f.label :date, "Date :" %>
  <%= f.date_field :date %>
  <br>
  <%= f.label :slots_id, "Select Slot :" %>
  <%= f.select :slots_id, @all_slots %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

<% elsif current_mentor %>
  <h3>Slots Available</h3>
  <% @slots.each do |sl| %>
    <div class="card" >
      <div class="card-body" >
        <div> <span>Start Time :</span> <%= sl.start_time.strftime("%I:%M %p") %> </div>
        <div> <span>End Time :</span> <%= sl.end_time.strftime("%I:%M %p") %> </div>
        <div> <span>Frequency :</span> 
        <% sl.frequency.each_with_index do |fre,i| %>
        <% if fre!= "" %>
        <% if i==1 %>
          <%= fre %>
        <% else %>
          <%= ", " + fre %>
        <% end %>
        <% end %>
        <% end %>
         </div>
      </div>
    </div>
    
  <% end %>

  <h3>Add Slots</h3>
  <%= render "mentors/slots/new" %> 



<% end %>
<p>Offered By:</p>
<h4><%= @offer["mentor"]["name"] %></h4>
<span class="" ><%= @offer['mentor']['designation'] %> , </span><span class="" ><%= @offer['mentor']['organization'] %></span>
<br><br>
<p><b>Bio :</b><%= @offer["mentor"]["bio"] %></p>
<p><b>Achievements :</b><%= @offer["mentor"]["achievements"]%></p>

<h5>Other Offers by Mentor :</h5>
<% @offer["mentor"]["offers"].each do |offer| %>
<% unless @offer["id"] == offer["id"] %>
<a href="/offers_show/<%= offer["id"]%>" style="text-decoration: none;" class="" ><div id="<%=offer["id"]%>" class="offers card m-3 btn-outline-success text-dark " style="width:18rem;"  >
                <div class="card-body" >
                
                <h5 class="card-title" ><%= offer['name']%></h5>
                <div class="text-info" >Price: ₹<%= offer['price']%>/hr</div>
                
                  <div class="card-title" >Mentor Details</div>
                  <div class=" card-title " ><%=  @offer["mentor"]  ["name"] %></div>
                       <span class="" ><%= @offer["mentor"]['designation']%> , </span>
                       <span class="" ><%= @offer["mentor"]['organization'] %></span>
                  </div>
                </div>
              </div>
              </div>
              </a>
<% end %>
              <% end %>